### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by francesco1119** [MadeiraData/ClrHttpRequest#5]
Hello,

I correctly registered the file that I downloaded from [here ](https://www.sqlservercentral.com/articles/http-requests-using-sqlclr)but when I run the GET query I receive this error:

```
Msg 6522, Level 16, State 1, Line 2
A .NET Framework error occurred during execution of user-defined routine or aggregate "clr_http_request": 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
System.Net.WebException: 
at System.Net.HttpWebRequest.GetResponse()
at UserDefinedFunctions.clr_http_request(String requestMethod, String url, String parameters, String headers, Int32 timeout, Boolean autoDecompress, Boolean convertResponseToBas64)
```

I'm on SQL Server 2019, I believe the C# request needs to be [updated ](https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel)

I also noticed that on SQLServerCentral the .zip file contains the .DLL , here on GitHub there is no .DLL ?

**Comment by EitanBlumin** [comment]
Hi Francesco,

The DLL you downloaded from SQLServer Central is outdated and does not support TLS.

Please refer to this repository releases page for a compiled DLL:

https://github.com/MadeiraData/ClrHttpRequest/releases/

Let me know if you require further assistance.

**Comment by francesco1119** [comment]
You are right, I was using the outdated one. 

I now have used the new one but I'm facing problems with the deployment query: `Incorrect syntax near...`

![Untitled](https://user-images.githubusercontent.com/3397477/91400260-a3635080-e83f-11ea-9863-19e5d867534f.png)


in fact the deployment query has a lot of troubles:

```
Msg 102, Level 15, State 1, Line 16
Incorrect syntax near ':'.
Msg 1038, Level 15, State 4, Line 19
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
Msg 1038, Level 15, State 4, Line 20
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
Msg 102, Level 15, State 1, Line 23
Incorrect syntax near ':'.
Msg 102, Level 15, State 1, Line 30
Incorrect syntax near ':'.
SQLCMD mode must be enabled to successfully execute this script.
Msg 911, Level 16, State 1, Line 57
Database '$(DatabaseName)' does not exist. Make sure that the name is entered correctly.
Msg 911, Level 16, State 1, Line 258
Database '$(DatabaseName)' does not exist. Make sure that the name is entered correctly.
```

**Comment by EitanBlumin** [comment]
You need to enable SQLCMD mode before executing this script.

For more info:
https://www.sqlshack.com/use-sqlcmd-commands-ssms-query-editor/

**Comment by francesco1119** [comment]
Thanks for the link, you teach me something today. 

I suggest you to add to the deployment query: 
```

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'lgn_clr_http_request')
    DROP LOGIN [lgn_clr_http_request]
IF  EXISTS (SELECT * FROM sys.asymmetric_keys WHERE name = N'key_clr_http_request')
    DROP LOGIN [key_clr_http_request]
```

**Comment by EitanBlumin** [comment]
Thanks for the suggestion, Francesco.

Those commands may have only been necessary in your case because you tried to deploy both mine and Eilert's version, so they conflicted with each other (they both have the same encryption key).
