### ISSUE TITLE
Timeout or Wrong Connection 

### ISSUE THREAD

**Issue by OneLonelly** [MadeiraData/ClrHttpRequest#7]
About year all worked fine (thanks a lot!) , but "The something strange in was-asked-site . Ghost bastards?" :  all requests to site begun to  finished with errors. Probably some changes in site was made. But Postman and KataonStudio return proper result still (with 200-Ok code). This problem concerns onli this site, not others. Does is need to correct anything in clrhttprequest source? Thanks for you advises! Good luck! 

Problem is : 

I send to Web-API from MS SQL Servers (2012, 2017, 2019) :

```
declare @response xml;
set @response = [dbo].[clr_http_request](N'POST', 
    N'http://cb-api.ozonru.me/v1/product/info/prices',  
    N'{"page": 1, "page_size": 10}', 
    N'<Headers>
     <Header Name="Client-Id">836</Header>
     <Header Name="Api-Key">0296d4f2-70a1-4c09-b507-904fd05567b9</Header>
     <Header Name="Content-Type">application/json</Header>
     </Headers>',  
    5000, 
    1,
    0);  
select @response;

```
Get the error:
_Message 6522, level 16, state 1, line 19
A .NET Framework error occurred during execution of user-defined routine or aggregate "clr_http_request": 
System.Net.WebException: Time is out
System.Net.WebException: 
   in System.Net.HttpWebRequest.GetResponse()
   in UserDefinedFunctions.clr_http_request(SqlString requestMethod, SqlString url, SqlString parameters, SqlString headers, SqlInt32 timeout, SqlBoolean autoDecompress, SqlBoolean convertResponseToBas64)_

**Comment by EitanBlumin** [comment]
Thank you for the report, my friend.

Based on what you describe, this could be a firewall-related issue.
Did you test using Postman from within the same machine as the SQL Server?

**Comment by OneLonelly** [comment]
Thanks a lot for fast reply. You almoust right. It was the problem with chanell proveder (somewhwere in the middle). Now all works right.
