### ISSUE TITLE
Calling External link - Linux

### ISSUE THREAD

**Issue by akhannahub** [MadeiraData/ClrHttpRequest#8]
How we can call external URL using this CLR mechanism in sql Server installed on linux. pls help

**Comment by EitanBlumin** [comment]
Hi @akhannahub , this CLR assembly is dependent on Windows system libraries. Therefore, I don't think it can work on a Linux system.

Perhaps re-writing the assembly in .NET Core could help?

**Comment by akhannahub** [comment]
I can try writing it in core. 

With .net i System.Security.SecurityException: Request for the permission of type 'System.Net.WebPermission

**Comment by EitanBlumin** [comment]
That sounds like a policy restriction issue at the environment level.

Perhaps you need to disable `clr strict security`? or try setting the database to `trustworthy`?

**Comment by akhannahub** [comment]
Done with all these options

**Comment by EitanBlumin** [comment]
Have you tried running a web request from outside SQL Server but on the same machine? Like from bash or Powershell or something like that?

**Comment by akhannahub** [comment]
Will try this approach once

**Comment by akhannahub** [comment]
Hi,

Thank you for reaching out. Following is what i did

1. I enabled broker in Database
2. Created an application with Sql dependency approach and once value gets
inserted in db table, i am calling outside web request and then update db
accordingly.

Hope above make some sense.

Regards

**Comment by EitanBlumin** [comment]
Ah, I see. That's an entirely different approach, though, @akhannahub .

But does that mean web requests outside the DB work on the same machine?

I just want to be sure whether the root cause here is the SQL Server itself, or the Linux machine it's hosted on.

**Comment by akhannahub** [comment]
Its definitely sql server. It does not allow web requests in linux
